build:
    environment:
        python: 3.7.1
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: pylint-run
                        use_website_config: true
                    - py-scrutinizer-run
    tests:
        before:
          - pip install -e.[test] && pip install tox-venv && make pyenv-versions && pyenv versions
        override:
            - command: tox .

filter:
    excluded_paths:
        - '*/test/*'

checks:
    python:
        code_rating: true
        duplicate_code: false
        classes_valid_slots: true
